threadCount=2
testMode=local_docker
browser=chrome:latest
headless=true
screenshotOnFail=true
videoOnFail=false
debugFail=false
debugMode=false
retainBrowser=false
browserSize=1052:630
highlight=false
stepDelay=0
pageWaitTimeout=30
elementWaitTimeout=4
elementWaitDelay=100
retryWait=200
retryTimeout=2000
colorsThreshold=80%
pointsThreshold=80%
sizeThreshold=2
pagesFolderPath=src/test/resources/pages
dataFolderPath=src/test/resources/data
imagesFolderPath=src/test/resources/images
