# Default configuration for AWS Lambda.
threadCount=4
testMode=local_playwright
browser=firefox
headless=true
screenshotOnFail=false
videoOnFail=false
debugFail=false
debugMode=false
retainBrowser=true
browserSize=1052:630
highlight=false
stepDelay=0
pageWaitTimeout=30
elementWaitTimeout=8
elementWaitDelay=100
pagesFolderPath=./src/test/resources/pages