<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.smarte2e</groupId>
    <artifactId>codeless-test-framework</artifactId>
    <version>1.8.5</version>
    <relativePath>./parent-pom.xml</relativePath>
  </parent>

  <artifactId>codeless-test-automation</artifactId>
  <version>1.8.5</version>
  <packaging>jar</packaging>

  <name>codeless-test-automation</name>
  <url>http://maven.apache.org</url>

  <properties>
    <threadCount>1</threadCount>
    <surefireReportDirectory>target/surefire-reports</surefireReportDirectory>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <version>4.12.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.5.4</version>
        <configuration>
          <!--suppress UnresolvedMavenProperty -->
          <threadCount>${threadCount}</threadCount>
          <suiteXmlFiles>
            <!--suppress UnresolvedMavenProperty -->
            <suiteXmlFile>${testSuite}</suiteXmlFile>
          </suiteXmlFiles>
          <!--<useSystemClassLoader>false</useSystemClassLoader>-->
          <argLine>-Xmx4g</argLine>
          <reportsDirectory>${surefireReportDirectory}</reportsDirectory>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
