name: SmartE2E Codeless Framework Java CI with Maven

on:
  push:
    branches:
      - "main"
      - "dev"
      - "feature**"
      - "fix**"
  pull_request:
    branches:
      - "main"
      - "dev"
      - "feature**"
      - "fix**"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  container-test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Java code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Unit Tests
        run: |
          mkdir -p target/surefire-reports-unit
          mvn clean test \
            -DtestSuite=./src/test/resources/testngUnitTests.xml \
            -DsurefireReportDirectory=target/surefire-reports-unit

      - name: Web Form Test - Local Docker - Linux Chrome latest
        run: |
          mkdir -p target/surefire-reports-local-docker
          mvn test \
            -DtestSuite=./src/test/resources/testngMethod.xml \
            -Dheadless=true \
            -DsurefireReportDirectory=target/surefire-reports-local-docker

      - name: Web Form Test (failed in order to record video and get screenshot)
        run: |
          mkdir -p target/surefire-reports-failed
          mvn test \
            -DtestSuite=./src/test/resources/testngMethod.xml \
            -Dheadless=true \
            -Dhighlight=true \
            -DdebugFail=true \
            -DscreenshotOnFail=true \
            -DvideoOnFail=true \
            -DsurefireReportDirectory=target/surefire-reports-failed
        continue-on-error: true

      - name: Web Form Test - Local Docker Auto - Linux Firefox latest
        run: |
          mkdir -p target/surefire-reports-local-docker-auto
          mvn test \
            -DtestSuite=./src/test/resources/testngMethod.xml \
            -DtestMode=local_docker_auto \
            -Dbrowser=firefox:latest \
            -Dheadless=true \
            -DsurefireReportDirectory=target/surefire-reports-local-docker-auto

      - name: Test - Local Playwright - Linux Firefox
        run: |
          mkdir -p target/surefire-reports-local-playwright
          mvn test \
            -DtestSuite=./src/test/resources/testngMethod.xml \
            -DtestMode=local_playwright \
            -Dbrowser=firefox \
            -DsurefireReportDirectory=target/surefire-reports-local-playwright

      - name: Test - Local Playwright - Linux Chromium - Retain Browser
        run: |
          mkdir -p target/surefire-reports-local-playwright
          mvn test \
            -DtestSuite=./src/test/resources/testng1.xml \
            -DtestMode=local_playwright \
            -Dbrowser=chromium \
            -DthreadCount=4 \
            -DretainBrowser=true \
            -DsurefireReportDirectory=target/surefire-reports-retain-browser

      # TODO: Uncomment when web element tests are fixed
      #- name: Web Element Unit Tests
      #  run: |
      #   mkdir -p target/surefire-reports-web-element-tests
      #   mvn test \
      #     -DtestSuite=./src/test/resources/testngWebElementSUnitTests.xml \
      #     -DsurefireReportDirectory=target/surefire-reports-web-element-tests

      # TODO: Uncomment when Maven exec plugin vulnerability is fixed.
      #- name: Test - AWS Local Docker - Chrome latest
      #  run: |
      #   mkdir -p target/surefire-reports-aws-local-docker
      #   mvn -f aws-local-pom.xml clean compile exec:java \
      #     -DthreadCount=4 \
      #     -DtestMode=local_docker \
      #     -Dbrowser=chrome:latest \
      #     -DtestngFile=testngMethod.xml \
      #     -DsurefireReportDirectory=target/surefire-reports-aws-local-docker

      # TODO: Fix AWS Device Farm Windows Edge.
      #- name: Test - AWS Device Farm - Windows Edge
      #  run: |
      #    mkdir -p target/surefire-reports-device-farm
      #    mvn test \
      #      -DtestSuite=./src/test/resources/testngMethod.xml \
      #      -DthreadCount=5 \
      #      -DtestMode=aws_device_farm \
      #      -Dbrowser=edge:latest \
      #      -DsurefireReportDirectory=target/surefire-reports-device-farm

      # TODO: Fix AWS Docker Chrome.
      #- name: Test - AWS Remote Docker - Linux Chrome
      #  run: |
      #    mkdir -p target/surefire-reports-aws-docker
      #    mvn test \
      #      -DtestSuite=./src/test/resources/testngMethod.xml \
      #      -DthreadCount=8 \
      #      -DtestMode=aws_docker \
      #      -Dbrowser=chrome:latest \
      #      -DsurefireReportDirectory=target/surefire-reports-aws-docker

      - name: Test - Local Playwright Accessibility Test - Chromium
        run: |
          mkdir -p target/surefire-reports-accessibility
          mvn test \
            -DtestSuite=./src/test/resources/testngMethod.xml \
            -DthreadCount=2 \
            -DtestMode=local_accessibility \
            -DsurefireReportDirectory=target/surefire-reports-accessibility

      - name: Upload Unit Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-unit
          path: target/surefire-reports-unit/**

      - name: Upload Local Docker Chrome Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-local-docker
          path: target/surefire-reports-local-docker/**

      - name: Upload Failed Debug Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-failed
          path: target/surefire-reports-failed/**

      - name: Upload Local Docker Auto Firefox Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-local-docker-auto
          path: target/surefire-reports-local-docker-auto/**

      - name: Upload Local Playwright Firefox Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-local-playwright
          path: target/surefire-reports-local-playwright/**

      - name: Upload Local Playwright Chromium Retain Browser Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-retain-browser
          path: target/surefire-reports-retain-browser/**

      - name: Upload Accessibility Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-accessibility
          path: target/surefire-reports-accessibility/**
