name: Java CI with Maven

on:
  push:
    branches:
      - "main"
      - "dev"
      - "feature**"
      - "fix**"
  pull_request:
    branches:
      - "main"
      - "dev"
      - "feature**"
      - "fix**"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  container-test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Java code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Unit Tests
        run: mvn test "-DtestSuite=./src/test/resources/testngUnitTests.xml" "-Dsurefire.reportsDirectory=target/surefire-reports-unit"

      - name: Web Form Test - Local Docker - Linux Chrome latest
        run: mvn clean test "-DtestSuite=./src/test/resources/testngMethod.xml" "-Dheadless=true" "-Dsurefire.reportsDirectory=target/surefire-reports-local-docker"

      - name: Web Form Test (failed to record video and get screenshot)
        run: mvn clean test "-DtestSuite=./src/test/resources/testngMethod.xml" "-Dheadless=true" "-Dhighlight=true" "-DdebugFail=true" "-DscreenshotOnFail=true" "-DvideoOnFail=true" "-Dsurefire.reportsDirectory=target/surefire-reports-failed"
        continue-on-error: true

      - name: Test - Local Playwright - Linux Firefox
        run: mvn clean test "-DtestSuite=./src/test/resources/testngMethod.xml" "-DtestMode=local_playwright" "-Dbrowser=firefox" "-Dsurefire.reportsDirectory=target/surefire-reports-playwright"

      - name: Test - Local Playwright Accessibility Test - Chromium
        run: mvn clean test "-DtestSuite=./src/test/resources/testngMethod.xml" "-DthreadCount=2" "-DtestMode=local_accessibility" "-Dsurefire.reportsDirectory=target/surefire-reports-accessibility"

      # Upload reports as separate artifacts
      - name: Upload Unit Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-unit
          path: target/surefire-reports-unit

      - name: Upload Local Docker Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-local-docker
          path: target/surefire-reports-local-docker

      - name: Upload Failed Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-failed
          path: target/surefire-reports-failed

      - name: Upload Playwright Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-playwright
          path: target/surefire-reports-playwright

      - name: Upload Accessibility Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-accessibility
          path: target/surefire-reports-accessibility
